"use client";

import React from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useForm } from "react-hook-form";
import { useToast } from "@/components/ui/use-toast";
import { createItem } from "./actions/create-item.action";
import { validation } from "@/validation/clients/create";
// Components
import { MainClientForm } from "@/components/clients/forms/main-client-form";
import { Button } from "@/components/ui/button";
import { Form } from "@/components/ui/form";

type FormData = z.infer<typeof validation>;

type CreateItemResult =
  | { message: string; error?: string }
  | { message: string; error: string }
  | void;

const CreateClientForm = ({ handleClose }: { handleClose: () => void }) => {
  const { toast } = useToast();
  const form = useForm<FormData>({
    resolver: zodResolver(validation),
    defaultValues: {
      // Main client info
      clientType: "BUSINESS",
      businessName: "",
      individualTitle: "",
      individualFirstName: "",
      individualLastName: "",
      clientLanguage: "",
      email: "",
      phone: "",

      // Main address
      address: "",
      city: "",
      countryCode: "CH",
      zipCode: undefined,
    },
  });

  const { isSubmitting } = form.formState;
  const watchClientType = form.watch("clientType") || "BUSINESS";

  const onSubmit = async (data: FormData) => {
    try {
      // Transform the form data to match the expected Client type
      const clientData = {
        ...data,
        code: "", // This will be generated by the server
        id: 0, // This will be generated by the server
      };

      const result = (await createItem(clientData as any)) as CreateItemResult;

      if (result && "error" in result) {
        throw new Error(result.error);
      }

      handleClose();
      toast({
        description: `Cliente ${
          data.businessName ||
          `${data.individualFirstName} ${data.individualLastName}`
        } creato con successo!`,
      });
    } catch (error) {
      toast({
        variant: "destructive",
        description: `Errore durante la creazione del cliente: ${
          error instanceof Error ? error.message : String(error)
        }`,
      });
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        {/* Main client form section */}
        <MainClientForm
          form={form}
          watchClientType={watchClientType}
          isSubmitting={isSubmitting}
        />

        {/* Submit button */}
        <Button type="submit" disabled={isSubmitting} className="w-full">
          {isSubmitting ? (
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              <span>Salvataggio in corso...</span>
            </div>
          ) : (
            "Salva Cliente"
          )}
        </Button>
      </form>
    </Form>
  );
};

export default CreateClientForm;
