import type { KnowledgeSource } from "@/types/assistants";

export const KNOWLEDGE_SOURCES_V1: KnowledgeSource[] = [
  {
    id: "common.modules_map",
    scope: "common",
    type: "doc",
    source: "docs/MANUALE-USO-MODULI.md",
    owner: "product",
    trustLevel: "high",
    updateStrategy: "manual-weekly",
    requiredForMvp: true,
  },
  {
    id: "common.user_guide",
    scope: "common",
    type: "doc",
    source: "docs/GUIDA-UTENTE-ADMIN-USER.md",
    owner: "support",
    trustLevel: "high",
    updateStrategy: "manual-monthly",
    requiredForMvp: true,
  },
  {
    id: "common.permissions_policy",
    scope: "common",
    type: "code-derived",
    source: "lib/permissions.ts",
    owner: "backend",
    trustLevel: "high",
    updateStrategy: "on-release",
    requiredForMvp: true,
  },
  {
    id: "vera.onboarding_playbook",
    scope: "vera",
    type: "kb",
    source: "knowledge/vera/onboarding-playbook.md",
    owner: "product",
    trustLevel: "medium",
    updateStrategy: "bi-weekly",
    requiredForMvp: true,
  },
  {
    id: "mira.operations_playbook",
    scope: "mira",
    type: "kb",
    source: "knowledge/mira/operations-playbook.md",
    owner: "operations",
    trustLevel: "high",
    updateStrategy: "weekly",
    requiredForMvp: true,
  },
  {
    id: "aura.crm_playbook",
    scope: "aura",
    type: "kb",
    source: "knowledge/aura/crm-playbook.md",
    owner: "sales",
    trustLevel: "high",
    updateStrategy: "weekly",
    requiredForMvp: true,
  },
];
