-- =============================================================================
-- Supporto tecnico FDM — ticketing (Fase 1)
-- Additive: nuove tabelle + bucket storage. Nessuna ALTER su tabelle esistenti.
-- Rollback: DROP delle sole entità create qui.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Categories (site_id NULL = globali)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_categories (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id     uuid REFERENCES public.sites(id) ON DELETE CASCADE,
  slug        text NOT NULL,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 0,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS support_categories_site_slug_uidx
  ON public.support_categories (site_id, slug)
  WHERE site_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS support_categories_global_slug_uidx
  ON public.support_categories (slug)
  WHERE site_id IS NULL;

CREATE INDEX IF NOT EXISTS support_categories_site_idx
  ON public.support_categories (site_id, sort_order);

INSERT INTO public.support_categories (site_id, slug, label, sort_order)
VALUES
  (NULL, 'accesso',     'Accesso e permessi',     10),
  (NULL, 'kanban',      'Kanban e task',          20),
  (NULL, 'produzione',  'Produzione e magazzino', 30),
  (NULL, 'documenti',   'Documenti e listino',    40),
  (NULL, 'anagrafiche', 'Anagrafiche',            50),
  (NULL, 'altro',       'Altro',                  90)
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Conversations
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_conversations (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id         uuid NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
  created_by      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status          text NOT NULL DEFAULT 'self_service'
                    CHECK (status IN ('self_service', 'escalated', 'abandoned')),
  user_query      text NOT NULL DEFAULT '',
  context         jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_conversations_site_user_idx
  ON public.support_conversations (site_id, created_by, created_at DESC);

DROP TRIGGER IF EXISTS trg_support_conversations_updated_at
  ON public.support_conversations;
CREATE TRIGGER trg_support_conversations_updated_at
  BEFORE UPDATE ON public.support_conversations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Tickets
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_number   integer GENERATED BY DEFAULT AS IDENTITY,
  site_id         uuid NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
  conversation_id uuid NOT NULL UNIQUE
                    REFERENCES public.support_conversations(id) ON DELETE RESTRICT,
  category_id     uuid REFERENCES public.support_categories(id) ON DELETE SET NULL,
  created_by      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assigned_to     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status          text NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open','in_progress','waiting_user','resolved','closed')),
  priority        text NOT NULL DEFAULT 'normal'
                    CHECK (priority IN ('low','normal','high','urgent')),
  source          text NOT NULL DEFAULT 'widget'
                    CHECK (source IN ('widget','error_boundary','admin')),
  subject         text NOT NULL,
  kb_attempted    boolean NOT NULL DEFAULT false,
  kb_article_ids  uuid[] NOT NULL DEFAULT '{}',
  resolved_at     timestamptz,
  closed_at       timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_tickets_site_status_idx
  ON public.support_tickets (site_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS support_tickets_assignee_idx
  ON public.support_tickets (assigned_to)
  WHERE assigned_to IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_tickets_created_by_idx
  ON public.support_tickets (created_by, created_at DESC);

DROP TRIGGER IF EXISTS trg_support_tickets_updated_at ON public.support_tickets;
CREATE TRIGGER trg_support_tickets_updated_at
  BEFORE UPDATE ON public.support_tickets
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Messages
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_messages (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL
                    REFERENCES public.support_conversations(id) ON DELETE CASCADE,
  ticket_id       uuid REFERENCES public.support_tickets(id) ON DELETE SET NULL,
  author_id       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  role            text NOT NULL
                    CHECK (role IN ('user','bot','agent','system')),
  body            text NOT NULL,
  kb_article_ids  uuid[] NOT NULL DEFAULT '{}',
  attachments     jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_messages_conversation_idx
  ON public.support_messages (conversation_id, created_at);

-- -----------------------------------------------------------------------------
-- Ticket events
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_ticket_events (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id   uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  actor_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  event_type  text NOT NULL,
  from_value  text,
  to_value    text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_ticket_events_ticket_idx
  ON public.support_ticket_events (ticket_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.support_log_ticket_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.support_ticket_events (ticket_id, actor_id, event_type, to_value)
    VALUES (NEW.id, auth.uid(), 'created', NEW.status);
    RETURN NEW;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.support_ticket_events
      (ticket_id, actor_id, event_type, from_value, to_value)
    VALUES (NEW.id, auth.uid(), 'status_change', OLD.status, NEW.status);
  END IF;

  IF NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
    INSERT INTO public.support_ticket_events
      (ticket_id, actor_id, event_type, from_value, to_value)
    VALUES (
      NEW.id,
      auth.uid(),
      'assign',
      OLD.assigned_to::text,
      NEW.assigned_to::text
    );
  END IF;

  IF NEW.priority IS DISTINCT FROM OLD.priority THEN
    INSERT INTO public.support_ticket_events
      (ticket_id, actor_id, event_type, from_value, to_value)
    VALUES (NEW.id, auth.uid(), 'priority_change', OLD.priority, NEW.priority);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_support_tickets_events ON public.support_tickets;
CREATE TRIGGER trg_support_tickets_events
  AFTER INSERT OR UPDATE ON public.support_tickets
  FOR EACH ROW EXECUTE FUNCTION public.support_log_ticket_event();

-- -----------------------------------------------------------------------------
-- Helpers (dopo le tabelle: le funzioni referenziano support_conversations)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.user_owns_support_conversation(target_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.support_conversations c
    WHERE c.id = target_id
      AND c.created_by = auth.uid()
      AND public.user_can_access_site(c.site_id)
  );
$$;

ALTER FUNCTION public.user_owns_support_conversation(uuid) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.user_owns_support_conversation(uuid)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.user_can_see_support_conversation(target_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.support_conversations c
    WHERE c.id = target_id
      AND (
        public.is_superadmin()
        OR (
          public.user_can_access_site(c.site_id)
          AND (
            c.created_by = auth.uid()
            OR public.user_is_site_admin(c.site_id)
          )
        )
      )
  );
$$;

ALTER FUNCTION public.user_can_see_support_conversation(uuid) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.user_can_see_support_conversation(uuid)
  TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
ALTER TABLE public.support_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS support_categories_select ON public.support_categories;
CREATE POLICY support_categories_select
  ON public.support_categories FOR SELECT TO authenticated
  USING (
    public.is_superadmin()
    OR site_id IS NULL
    OR public.user_can_access_site(site_id)
  );

DROP POLICY IF EXISTS support_categories_write ON public.support_categories;
CREATE POLICY support_categories_write
  ON public.support_categories FOR ALL TO authenticated
  USING (
    public.is_superadmin()
    OR (site_id IS NOT NULL AND public.user_is_site_admin(site_id))
  )
  WITH CHECK (
    public.is_superadmin()
    OR (site_id IS NOT NULL AND public.user_is_site_admin(site_id))
  );

DROP POLICY IF EXISTS support_conversations_select ON public.support_conversations;
CREATE POLICY support_conversations_select
  ON public.support_conversations FOR SELECT TO authenticated
  USING (
    public.is_superadmin()
    OR (
      public.user_can_access_site(site_id)
      AND (created_by = auth.uid() OR public.user_is_site_admin(site_id))
    )
  );

DROP POLICY IF EXISTS support_conversations_insert ON public.support_conversations;
CREATE POLICY support_conversations_insert
  ON public.support_conversations FOR INSERT TO authenticated
  WITH CHECK (
    public.user_can_access_site(site_id)
    AND created_by = auth.uid()
  );

DROP POLICY IF EXISTS support_conversations_update ON public.support_conversations;
CREATE POLICY support_conversations_update
  ON public.support_conversations FOR UPDATE TO authenticated
  USING (
    public.is_superadmin()
    OR (
      public.user_can_access_site(site_id)
      AND (created_by = auth.uid() OR public.user_is_site_admin(site_id))
    )
  )
  WITH CHECK (
    public.is_superadmin()
    OR (
      public.user_can_access_site(site_id)
      AND (created_by = auth.uid() OR public.user_is_site_admin(site_id))
    )
  );

DROP POLICY IF EXISTS support_tickets_select ON public.support_tickets;
CREATE POLICY support_tickets_select
  ON public.support_tickets FOR SELECT TO authenticated
  USING (
    public.is_superadmin()
    OR (
      public.user_can_access_site(site_id)
      AND (created_by = auth.uid() OR public.user_is_site_admin(site_id))
    )
  );

DROP POLICY IF EXISTS support_tickets_insert ON public.support_tickets;
CREATE POLICY support_tickets_insert
  ON public.support_tickets FOR INSERT TO authenticated
  WITH CHECK (
    public.user_can_access_site(site_id)
    AND created_by = auth.uid()
    AND public.user_owns_support_conversation(conversation_id)
  );

DROP POLICY IF EXISTS support_tickets_update ON public.support_tickets;
CREATE POLICY support_tickets_update
  ON public.support_tickets FOR UPDATE TO authenticated
  USING (
    public.is_superadmin()
    OR public.user_is_site_admin(site_id)
    OR (
      created_by = auth.uid()
      AND public.user_can_access_site(site_id)
    )
  )
  WITH CHECK (
    public.is_superadmin()
    OR public.user_is_site_admin(site_id)
    OR (
      created_by = auth.uid()
      AND public.user_can_access_site(site_id)
    )
  );

DROP POLICY IF EXISTS support_messages_select ON public.support_messages;
CREATE POLICY support_messages_select
  ON public.support_messages FOR SELECT TO authenticated
  USING (public.user_can_see_support_conversation(conversation_id));

DROP POLICY IF EXISTS support_messages_insert ON public.support_messages;
CREATE POLICY support_messages_insert
  ON public.support_messages FOR INSERT TO authenticated
  WITH CHECK (
    public.user_can_see_support_conversation(conversation_id)
    AND (
      (
        public.user_owns_support_conversation(conversation_id)
        AND role IN ('user', 'bot', 'system')
        AND (author_id IS NULL OR author_id = auth.uid())
      )
      OR (
        role = 'agent'
        AND EXISTS (
          SELECT 1 FROM public.support_conversations c
          WHERE c.id = conversation_id
            AND (
              public.is_superadmin()
              OR public.user_is_site_admin(c.site_id)
            )
        )
      )
    )
  );

DROP POLICY IF EXISTS support_ticket_events_select ON public.support_ticket_events;
CREATE POLICY support_ticket_events_select
  ON public.support_ticket_events FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.support_tickets t
      WHERE t.id = ticket_id
        AND (
          public.is_superadmin()
          OR (
            public.user_can_access_site(t.site_id)
            AND (t.created_by = auth.uid() OR public.user_is_site_admin(t.site_id))
          )
        )
    )
  );

DROP POLICY IF EXISTS support_ticket_events_insert ON public.support_ticket_events;
CREATE POLICY support_ticket_events_insert
  ON public.support_ticket_events FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.support_tickets t
      WHERE t.id = ticket_id
        AND (public.is_superadmin() OR public.user_is_site_admin(t.site_id))
    )
  );

GRANT SELECT, INSERT, UPDATE ON public.support_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.support_conversations TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.support_tickets TO authenticated;
GRANT SELECT, INSERT ON public.support_messages TO authenticated;
GRANT SELECT, INSERT ON public.support_ticket_events TO authenticated;

GRANT ALL ON public.support_categories TO service_role;
GRANT ALL ON public.support_conversations TO service_role;
GRANT ALL ON public.support_tickets TO service_role;
GRANT ALL ON public.support_messages TO service_role;
GRANT ALL ON public.support_ticket_events TO service_role;

-- -----------------------------------------------------------------------------
-- Storage bucket (private) — path {site_id}/{conversation_id}/{file}
-- -----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'support',
  'support',
  false,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "support_storage_select" ON storage.objects;
CREATE POLICY "support_storage_select"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'support'
    AND (
      public.is_superadmin()
      OR public.user_can_access_site(public.get_site_id_from_storage_path(name))
    )
  );

DROP POLICY IF EXISTS "support_storage_insert" ON storage.objects;
CREATE POLICY "support_storage_insert"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'support'
    AND public.user_can_access_site(public.get_site_id_from_storage_path(name))
  );

DROP POLICY IF EXISTS "support_storage_delete" ON storage.objects;
CREATE POLICY "support_storage_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'support'
    AND (
      public.is_superadmin()
      OR public.user_is_site_admin(public.get_site_id_from_storage_path(name))
    )
  );

-- -----------------------------------------------------------------------------
-- Realtime
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'support_tickets'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.support_tickets;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'support_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.support_messages;
  END IF;
END;
$$;

COMMIT;
